### ISSUE TITLE
Set up tests

### ISSUE THREAD

**Issue by plexus** [plexus/unrepl.el#1]
We really should get some tests going. I've used ert before, I'm open to something else as well.

This includes setting up CI, you can look at plexus/clj-parse for inspiration.

Just a single test would already be great, to have the setup there, then we can expand on it.

**Comment by volrath** [comment]
couldn't find [clj-parse](https://github.com/plexus/clj-parse), is it anywhere else?

**Comment by plexus** [comment]
Oh seems I put that one under Lambda Island... 

https://github.com/lambdaisland/clj-parse

**Comment by volrath** [comment]
Ok great, thanks!
